site_name: MSE CSUF
# site_url: "https://your-username.github.io/your-repo-name/" # Recommended to set this for correct links
site_url: https://conglesolutionx.github.io/CSUF_MSE/
nav:
  - Introduction: 'index.md'
  - Syllabus: 'Syllabus.md'
  - Textbook: 'Chapter_1/Chapter_1.md'

theme:
  name: material
  # The 'custom_dir' line is removed to fix the build error, as the directory does not exist.
  # If you create an 'overrides' directory later, you can add 'custom_dir: overrides' back.
  icon:
    logo: material/library-shelves

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: orange
      accent: amber

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep orange
      accent: green

# Merged all markdown extensions under a single key.
markdown_extensions:
  - smarty
  - toc:
      permalink: true
  - sane_lists
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Plugins
plugins:
  - search

# # To enable language toggle, uncomment this section and ensure you have
# # the language-specific files in subdirectories (e.g., 'en', 'vi').
# extra:
#   alternate:
#     - name: English
#       link: /en/
#       lang: en
#     - name: Vietnamese
#       link: /vi/
#       lang: vi
