site_name: MSE CSUF
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/library-shelves
  
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: orange
      accent: amber

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep orange
      accent: green

# # Add toggle for English and Vietnamese language
#   extra:
#   alternate:
#     - name: English
#       link: /en/ 
#       lang: en
#     - name: Vietnamese
#       link: /vi/
#       lang: vi